library(car)
fold <- 'C:/Users/murem/OneDrive/Desktop/BME/Datasets'
setwd(fold)
getwd()
Blooms <- read.table('Blooms.txt', header=TRUE)
head(Blooms)
is.numeric(Blooms$SQBLOOMS)
is.factor(Blooms$SQBLOOMS)
is.factor(Blooms$BED)
is.numeric(Blooms$BED)
Blooms$BED <- as.factor(Blooms$BED)
is.factor(Blooms$BED)
is.numeric(Blooms$WATER)
is.factor(Blooms$WATER)
Blooms$WATER<- as.factor(Blooms$WATER)
is.factor(Blooms$WATER)
is.numeric(Blooms$SHADE)
is.factor(Blooms$SHADE)
Blooms$SHADE <- as.factor(Blooms$SHADE)
is.factor(Blooms$SHADE)
summary(Blooms)
model1 <- lm(Blooms$SQBLOOMS~ BED+ WATER+SHADE, data=Blooms)
summary(model1)
crPlots(model1)
crPlots(model1)
residualPlots(model1)
plot(Blooms$SQBLOOMS, predict(model1), xlab= 'Observed vaues', ylab= 'Predcted values')
anova(model1)
Anova(model1)
