fold <- "C:/Users/murem/OneDrive/Desktop/BME/Datasets/Datasets"
setwd(fold)
getwd()
Fats<- read.table ('WeightFat.txt', head=TRUE)
is.numeric(Fats$WEIGHT)
is.factor(Fats$WEIGHT)
is.factor(Fats$FAT)
is.numeric(Fats$FAT)
Regr<- lm(Fats$FAT~ Fats$WEIGHT)
summary(Regr)
Regr <- lm(FAT ~ WEIGHT, data= Fats)
summary(Regr)
plot(Fats$WEIGHT, Fats$FAT)
abline(Regr)
abline(a=26.88558, b= 0.02069, col='blue')
