fold <- "C:/Users/murem/OneDrive/Desktop/BME/Datasets"
setwd(fold)
getwd()
Soyabeans <- read.table("SoyaBeans.txt", header=T)
head(Soyabeans)
is.factor(Soyabeans$WDKLR)
Soyabeans$WDKLR <- as.factor(Soyabeans$WDKLR)
is.numeric(Soyabeans$DAMAGE)
summary(Soyabeans)
Soyabeans$SQRTDAMAGE <- sqrt(Soyabeans$DAMAGE)
head(Soyabeans)
Soyabeans$LOGDAMAGE <- log(Soyabeans$DAMAGE)
Soyabeans$inversDAMAGE <- (-1/ (1+Soyabeans$DAMAGE))
head(Soyabeans)
par(mfrow = c(2, 2))  
plot(DAMAGE ~ WDKLR, data=Soyabeans)
mod1 <- lm(DAMAGE ~ WDKLR, data=Soyabeans)
plot(SQRTDAMAGE ~ WDKLR, data=Soyabeans)
mod2 <- lm(SQRTDAMAGE ~ WDKLR, data=Soyabeans)
plot(LOGDAMAGE ~ WDKLR, data=Soyabeans)
plot(inversDAMAGE~ WDKLR, data=Soyabeans)
residualPlots(mod1)
